### ISSUE TITLE
html_meta_tags extension only uses basic info for copyright and rights values, does not use metadata from images

### ISSUE THREAD

**Issue by JesseHC** [zenphoto/zenphoto#1296]
The html_meta_tags extension only puts generic copyright info for copyright and rights, and does use the metadata from the images.

In html_meta_tags.php for copyright, on line 365:
```
		if (getOption('htmlmeta_name-copyright')) {
			$meta .= '<meta name="copyright" content=" (c) ' . FULLWEBPATH . ' - ' . $author . '">' . "\n";
		}
```
For rights it only displays the author, on line 368:
```
		if (getOption('htmlmeta_name-rights')) {
			$meta .= '<meta name="rights" content="' . $author . '">' . "\n";
		}
```

Ideally it would be using the Copyright Notice field for copyright and Copyright Holder for rights, which can already be pulled in from Options-Image-Metadata.

It would be nice if there was a way to set a value for the copyright notice and for the copyright location for the site. Currently there is a similar field for IPTC imbedding in the Image options, but that is only used if there is not an IPTC copyright notice in the image, and it is then added to cached images.

There is also an option in the sitemap-extended extension for "Google - URL to image license". That's optional and only used if the Google extension is also set in sitemap-extended.

If we allowed the user to declare values for Copyright and the Copyright info URL in Image options, similar to those under IPTC Copyright in image metadata, the Copyright could then be pulled by html_meta_tags as a fallback if the image does not contain it. The Copyright value could continue to be used by IPTC imbedding, and the Copyright info URL could also be pulled by sitemap-extended.

One last thing, the page for the extension- https://www.zenphoto.org/news/html_meta_tags/
says:
_"This extension is officially supported but not included in the ZenphotoCMS release."_
when it is included in the release.

The link on the page (which I think you know about)- _"Info & download (GitHub)"_
goes here-
https://www.zenphoto.org/documentation/plugins/_zp-extensions---html_meta_tags.html
which redirects here-
https://docs.zenphoto.org/

**Comment by acrylian** [comment]
>If we allowed the user to declare values for Copyright and the Copyright info URL in Image options, similar to those under IPTC Copyright in image metadata, the Copyright could then be pulled by html_meta_tags as a fallback if the image does not contain it. 

Yes, we assume the author/owner/the site itself are the copyrights holder right now. Add those two option fields seems like a good idea and that could even replace the IPTC one we have right now.

I will also take a look to use the copyright metadata info if available.

Thanks for the note about the outdated entry on our site. It must have been that way for years without anyone noticing…

**Comment by acrylian** [comment]
I implemented new options (the old copyright info option will be renamed via setup) although not yet in the html_meta_tags plugin or the sitemaps plugin where the copyright url option will make the plugin one obsolete later on.

**Comment by acrylian** [comment]
> Ideally it would be using the Copyright Notice field for copyright and Copyright Holder for rights, which can already be pulled in from Options-Image-Metadata.

Actually the author field should get the copy rights holder. The "rights" meta tag actually can be removed as it is of no relevance as are some others like keywords, at least not for SEO.

**Comment by acrylian** [comment]
1.5.8RC/Master has now a change implemented in html_meta_tags. Please try. Note that you cannot just try the plugin but need to install 1.5.8RC.

**Comment by JesseHC** [comment]
When I added the latest build and tried to run setup I got a blank page and this error message in zp-data/debug.log-

```
{1523:Thu, 08 Apr 2021 04:38:53 GMT}
  EXCEPTION (0): Call to undefined function reconfigureCS() in /Applications/MAMP/htdocs/zenphoto158test/zp-core/setup.php on line 17
```

When I tried to go back to the Admin page I got an Object not found error page-

Zenphoto Error: the requested object was not found.
Album: zp-core/admin 

When I tried again, I was able to get into Admin and run setup successfully (though it was still showing the zp-core/zp-extensions/elfinder/php/.tmp warning).


The copyright info locations under Image-Options seems to be correct, thanks for making those changes! This is super nit-picky, so feel free to ignore, but half the option listings use colons at the end and half don't. 

For the meta tags-

"copyright" is correctly pulling copyright info from metadata. Fallback to Zenphoto user set value is working.

"publisher" and "creator" are using Zenphoto Copyright URL, they probably should be first trying to use Photoshop URL or XMP Web Statement metadata, where that value is normally stored in images, though I'm not sure Zenphoto is pulling this.

"author" is using Zenphoto user supplied name and should be using either Artist or Byline (EXIF "Artist" or IPTC "By-line"), with the fallback to Zenphoto's user value.


Though it seems Google no longer cares about author-
https://support.google.com/webmasters/answer/6083347?hl=en

Google really wants people to use structured data based on schema.org-
https://developers.google.com/search/docs/guides/intro-structured-data?visit_id=637534618380798391-2556225057&rd=1
https://schema.org/

Maybe something for the future?
https://schema.org/Photograph

Or adding structure to Image info?
https://schema.org/ImageObject

Thanks for doing all this. I think it will make a nice improvement for users with their metadata filled out correctly.

**Comment by acrylian** [comment]
Thanks for the issue report. Apparently either we forgot to fix an instance of thte changed version name (CS was fixed to CSS) or it was just a cache issue somehow. The other error is a security measure basically.

> When I tried again, I was able to get into Admin and run setup successfully (though it was still showing the zp-core/zp-extensions/elfinder/php/.tmp warning).

That's from your upload and the local file system, you have to remove that yourself. Or set your FTP client to skip such files.

> "publisher" and "creator" are using Zenphoto Copyright URL, they probably should be first trying to use Photoshop URL or XMP Web Statement metadata, where that value is normally stored in images, though I'm not sure Zenphoto is pulling this.

We can only use the fields available in the database. Photoshop URL is a vendor specific field we will not read anyawy. XMP is only available with special plugin and then mapped to the predefined fields. We really can't use all type of custom fields as EXIF is sadly not a fixed standard.

Google does not care about a lot of meta fields… Structure data is on the list for sometime later but not right now. This current change is the last before 1.5.8 anyway. The most important is the actual page content anyway.

While we at this we are doing some more changes as I am going to add a Zenpage page selector to the copyright url. and we will add similar options on the gallery options to be used site wide also as general fallback to the image options.

**Comment by JesseHC** [comment]
> That's from your upload and the local file system, you have to remove that yourself. Or set your FTP client to skip such files.

I've gotten that zp-core/zp-extensions/elfinder/php/.tmp warning the two separate times I've tried installing different versions of 1.5.8RC.

![Zenphoto 1 5 8 elFinder tmp warning](https://user-images.githubusercontent.com/82089671/113998909-5e0ff400-980e-11eb-9109-dc03317eaac6.png)


It appears to be an issue with elFinder and it is missing the .tmp folder.

I'm simply extracting the .zip file. If I do check for it with hidden files turned on, there is no .tmp folder there.

You can compare here to see that it is missing the folder-

https://github.com/zenphoto/zenphoto/tree/master/zp-core/zp-extensions/elFinder/php

https://github.com/Studio-42/elFinder/tree/master/php

**Comment by acrylian** [comment]
We generally take third party tools as they are and don't alter them. No idea where this comes from but it contains a .htaccess file on my installs. Generally the .tmp folder is from some file system stuff, just like DS_Store files from Mac always are listed on a local server. Aferall this is just a warning. Anyway, I will remove that folder with the next commit.

Also i just noticed we indeed have the `IPTCBy-line" filed so I will add that as a fallback.

**Comment by JesseHC** [comment]
While testing a sitemap issue in 1.5.7*, that appears to now be fixed in 1.5.8RC, I noticed that there seems to be an issue with the license info being added to image sitemaps in 1.5.8RC. It appears this change [017ad1a](https://github.com/zenphoto/zenphoto/commit/017ad1a2d1ec9ce639f4ca10d90d1be71f8a2d4c) in _zp-core/zp-extensions/sitemap-extended.php_ might be the cause.

In 1.5.7 I get-
`<image:license>https://domain.com/copyright/</image:license>`

In 1.5.8RC I now get-
```
<image:license>
a:1:{s:5:"en_US";s:35:"https://domain.com/copyright/";}
</image:license>
```

The same extra a:1:{s:5:"en_US";s:35:" ";} was being added to all entries.

* The original issue was album sitemaps were generating extra pages that didn't exist in 1.5.7, so lots of extra "/page/2" in them that would cause search errors, because it appears to be basing the results off the default thumbnails per page theme options and not the custom settings that were actually being used that no longer had those extra pages. Like I said though, that issue now appears to be fixed.

**Comment by JesseHC** [comment]
> We generally take third party tools as they are and don't alter them. No idea where this comes from but it contains a .htaccess file on my installs. Generally the .tmp folder is from some file system stuff, just like DS_Store files from Mac always are listed on a local server. Aferall this is just a warning. Anyway, I will remove that folder with the next commit.

![elFinder warning still in setup](https://user-images.githubusercontent.com/82089671/117536461-fdf8a300-afaf-11eb-999c-f16c12c58219.png)

The issue with the elFinder warning during setup is still there. I bring it up because I noticed [other people having issues with it](https://forum.zenphoto.org/discussion/comment/1983234/#Comment_1983234) and wanted to let you know that a solution for it seems to have been posted [here](https://forum.zenphoto.org/discussion/comment/1983238/#Comment_1983238).

**Comment by acrylian** [comment]
Please do not mix different topics in one ticket. The .tmp file is not part of the package and like the other files mentioned excluded from the package generation now. elFinder generates this temp file afterwards when running which we cannot control. It simple reports all files that are not part of the package. As said it is a note for the site user to decide what to do.

Thanks, for the actual ticket part. That must be form am older value inbetween I think. The new copyright site url option (Options -> Gallery or Options > Image) that is used here is actually not mulitlingual. Try to resave the related option to see if that fixes anything.

**Comment by acrylian** [comment]
The multilingual issue is actualy not from the new options but from the sitemap plugin own option which was indeed set to multilingual although it is meant for an URL only and should not . This is now fixed in 1.5.8RC: You still need to re-save it.
